import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { AiFillGithub } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>v50!</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.center}>
					<Image src={"/v50guy.png"} width={200} height={200} alt={"v50-guy"} style={{borderRadius: "24px"}}></Image>
					<p>V50</p>
				</div>

				<div className={styles.description}>
					<div>
						<a href="https://www.abandon.work" target="_blank" rel="noopener noreferrer">
							By <AiFillGithub />
						</a>
					</div>
				</div>
			</main>
		</>
	);
}
